# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - 
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: Docker@2
  inputs:
    containerRegistry: 'ACR-SC'
    repository: 'naveen12'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'

- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'Free Trial(f87aaef8-047b-488d-bf1c-b9837e226a9f)'
    appName: 'azuredeployacr'
    containers: 'naveen12'

